### ISSUE TITLE
vJoy Output

### ISSUE THREAD

**Issue by joe2035** [lshachar/WiiBalanceWalker#5]
Hi, I am trying to use the wbb with a vr game but this one doesn’t read keyboard inputs, but it can work with a controller. So I tried to enable vJoy output and windows seems to detect it as I can see the vJoy Device in game controllers. I’ve done the calibration process and everything works as I would, but when a go to the game I can’t move. It seems like windows sees the vJoy device but the game doesn’t. I also tried with an other normal game and the wasd  keys works but the vJoy isn’t detected either. Could you help me ?

**Comment by joe2035** [comment]
Well today I tried on a third game which is Star Wars squadron just to see if the game detects the vJoy in the controller settings, and it does, but as a joystick only and not as a controller (like an Xbox or a ps controller). I don’t know if it is meant to be like that but I think my problem comes form this. The games detects the vJoy as a real joystick like for a hotas setup and not as a game controller, so games that doesn’t support hotas just don’t work. Is there a way to set the vJoy as virtual controller instead of a virtual joystick or other stuff to make it work ?

**Comment by lshachar** [comment]
Try [Xbox 360 Controller Emulato](https://www.x360ce.com/), which will use your virtual joystick device to emulate an xbox controller.

**Comment by joe2035** [comment]
Ok so I downloaded x360ce and now everything works as I want, this is amazing !
Thanks a lot for your help
