### ISSUE TITLE
Cannot read data from 'wiimote'

### ISSUE THREAD

**Issue by Engired** [lshachar/WiiBalanceWalker#9]
Error message reads as such: "Error reading data from Wiimote...is it connected?"
Cannot find a single troubleshooting step that works, both vjoy and Julian Löhr HID have been reinstalled. (RVL-021 Wii Balance Board, C/RVL-BC-AUS)

Status reads as such:
vJoy ConsoleÆ¢]g¬
Vendor: Shaul Eizikovich
Product :vJoy - Virtual Joystick
Version Number:2.1.8
vJoy Device 1 is free
vJoy Device 1 capabilities:
Number of buttons		16
Number of Continuous POVs	0
Number of Descrete POVs		0
Axis X		Yes
Axis Y		Yes
Axis Z		Yes
Axis Rx		Yes
Axis Ry		Yes
Axis Rz		Yes
Version of Driver Matches DLL Version (218)
Acquired: vJoy device number 1.

vJoyList also lists #1 as red, not sure if normal.

Current computer has also had many problems in past with wiimote.

OS: Windows10
CPU: AMD Ryzen 5 2600x
Motherboard: B450 Aorus M
Bluetooth adapter is PCIE, lowest slot, name is GC-WBAX200. May be a similar model.

All drivers up to date.

Current HID list is as follows
![Ca24pture](https://user-images.githubusercontent.com/50287514/140601205-468539cf-2954-43b8-adf7-740610af3ac6.PNG)
:

I cannot think of anything else I can provide for information, hopefully this is everything needed.

**Comment by jaimydk** [comment]
I have the exact same problem. And cant find a solution :(

**Comment by lshachar** [comment]
The problem you're experiencing is in WiimoteLib. I did not write it, [only lightly changed it.](https://github.com/lshachar/WiimoteLib) 
Brian Peek wrote it, and hopefuly you might get some help by posting your issue [there](https://github.com/BrianPeek/WiimoteLib).

Also, googling your error message brings a couple of results, but I can't tell you if they're any good..

afair, Julian Löhr's work has nothing to do with WiimoteLib. having it installed could possibly be a related to the problem.

**Comment by Engired** [comment]
I have done heaps of research by googling but nobody seems to have anything close to the problem that I have. I'll see if the people over at WiimoteLib know a bit more about it.

**Comment by kdude729** [comment]
so how do i use your link to change wiimotelib?

**Comment by AlmightyMikkel** [comment]
> I have done heaps of research by googling but nobody seems to have anything close to the problem that I have. I'll see if the people over at WiimoteLib know a bit more about it.

Any news on this?

**Comment by Engired** [comment]
No, I have tried some other things to make it work but it looks like it
isn't going to work.

**Comment by AlmightyMikkel** [comment]
> 

I managed to get it to work!
After searching a bit, I realized I had the HID wiimote driver installed. Uninstall it and reboot your pc. It should work!
Do you have any suggestions on how I add multiple boards?
I need to use two boards at the same time :)

**Comment by AlmightyMikkel** [comment]
@lshachar How was it intended to use multiple boards at the same time?
I cannot connect a second board through the device manager, do you have any suggestions?

**Comment by lshachar** [comment]
Unfortunately I only have this single wii balance board, and I don't own any other wii devices, so I really can't help you with that.
The library part of this project (WiimoteLib) very likely supports multiple balance boards, but I don't imagine that the original programmer of the wiiBalanceWalker software ever tried getting it to work with more than a single balance board.
In other words, you would have to do a lot of self learning... good luck

**Comment by Engired** [comment]
I uninstalled the HID wiimote driver, and it works now. Might need to be put down as a warning.
